version: '3.8'

services:
  mongo:
    image: arm64v8/mongo:4.4.18
    container_name: mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: louis
      MONGO_INITDB_ROOT_PASSWORD: 32767Getcoinn
    volumes:
      - ./mongo_data:/data/db
      - ./init:/docker-entrypoint-initdb.d/init-mongo.js:ro