version: '3.8'

services:
  quikbin-backend:
    image: node:lts
    working_dir: /app
    volumes:
      - ./:/app
    command: sh -c "npm install && node server.js"
    ports:
      - "3002:3000"
    environment:
      - NODE_ENV=development
    restart: unless-stopped
